[build]
preload = [
  "./libraries/bun-plugins/register.ts"
]

[test]
coverage = true
coverageReporter = ["lcov"]
coverageSkipTestFiles = true
preload = [
	"./config/happydom.ts",
	"./libraries/react/testing/bun"
]
