name: 'Create Release'
description: 'Creates a new release based on conventional commits'

inputs:
  github-token:
    description: 'GitHub token for creating the release'
    required: true

outputs:
  release_created:
    description: 'Whether a release was created'
    value: ${{ steps.semver.outputs.released }}
  version:
    description: 'The version that was released'
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Checkout with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine Next Version
      id: semver
      uses: grumpy-programmer/conventional-commits-semver-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Create Release
      if: ${{ steps.semver.outputs.released == 'true' }}
      uses: ncipollo/release-action@v1.12.0
      with:
        body: "See the changelog for details."
        draft: false
        prerelease: false
        release_name: Release ${{ steps.semver.outputs.version }}
        tag_name: ${{ steps.semver.outputs.version }}
        token: ${{ inputs.github-token }}
