name: 'Create Convco Release'
description: 'Create a new release based on Conventional Commits'

inputs:
  dry-run:
    description: 'Run in dry-run mode without making actual changes'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for creating the release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history

    - name: Fetch all tags
      run: |
        git fetch --prune --tags origin
        git fetch --all
      shell: bash

    - name: ASDF Setup
      uses: ./.github/actions/asdf-setup
      with:
        plugins: '["bun@latest"]'

    - name: Sync package.json version with latest tag
      id: sync-version
      shell: bash
      run: |
        # List tags for debugging
        echo "Available tags:"
        git tag -l
        
        # Get latest tag using git tag sorting
        latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n1)
        if [ -z "$latest_tag" ]; then
          echo "Warning: Could not find any tags. Using initial version."
          latest_tag="v0.0.0"
        fi
        
        echo "Latest tag: $latest_tag"
        latest_tag_version=${latest_tag#v}
        
        # Get the current package.json version
        package_version=$(node -p "require('./package.json').version")
        echo "Package.json version: $package_version"

        # Compare and update package.json if necessary
        if [ "$(printf '%s\n' "$latest_tag_version" "$package_version" | sort -V | head -n1)" != "$latest_tag_version" ]; then
          echo "Updating package.json version from $package_version to $latest_tag_version"
          jq --arg version "$latest_tag_version" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(release): v$latest_tag_version"
          git push origin HEAD:main
        fi

    - name: Determine new version and update package.json
      id: version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Configure git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if [ "${{ inputs.dry-run }}" != "true" ] && [ "$current_branch" = "main" ]; then
          # Configure git to use the token (only when actually making changes)
          git remote set-url origin "https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        fi

        # Get current branch name
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        echo "Current branch: $current_branch"
        
        # Get latest tag using git tag sorting
        latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n1)
        if [ -z "$latest_tag" ]; then
          echo "No tags found. Using v0.0.0 as base version."
          latest_tag="v0.0.0"
        fi
        
        # Get current package.json version
        current_version=$(node -p "require('./package.json').version")
        
        echo "📦 Current Versions:"
        echo "  • package.json: v$current_version"
        echo "  • Latest tag:   $latest_tag"
        
        # Create a temporary copy of package.json for version computation
        cp package.json package.json.temp
        
        # First, update the temporary package.json to match the latest tag
        latest_version=${latest_tag#v}
        jq --arg version "$latest_version" '.version = $version' package.json.temp > package.json.temp2 && mv package.json.temp2 package.json.temp
        
        # Get conventional commits since last tag for analysis
        echo -e "\n📋 Commits since $latest_tag:"
        git log $latest_tag..HEAD --pretty=format:"  • %s" --no-merges

        # Run standard-version in dry-run mode to determine next version
        echo -e "\n🔄 Computing next version..."
        if ! bunx standard-version --release-as auto --skip.tag --dry-run > version_output.txt 2>&1; then
          echo "Error: Failed to determine new version"
          rm package.json.temp version_output.txt
          exit 1
        fi

        # Extract the computed new version
        new_version=$(node -p "require('./package.json.temp').version")
        
        # Determine bump type by comparing versions
        if [ "$(echo $latest_version | cut -d. -f1)" != "$(echo $new_version | cut -d. -f1)" ]; then
          bump_type="major"
        elif [ "$(echo $latest_version | cut -d. -f2)" != "$(echo $new_version | cut -d. -f2)" ]; then
          bump_type="minor"
        else
          bump_type="patch"
        fi
        
        echo -e "\n📈 Version Impact:"
        echo "  • Current:  $latest_tag"
        echo "  • Next:     v$new_version"
        echo "  • Type:     $bump_type bump"

        if [ "${{ inputs.dry-run }}" != "true" ] && [ "$current_branch" = "main" ]; then
          echo -e "\n⚡ Applying changes..."
          mv package.json.temp package.json
          echo "release_needed=true" >> $GITHUB_OUTPUT
        else
          echo -e "\n🔍 DRY RUN - No changes will be made"
          rm package.json.temp
          echo "release_needed=false" >> $GITHUB_OUTPUT
        fi
        
        # Cleanup
        rm -f version_output.txt
        echo "version=$new_version" >> $GITHUB_OUTPUT

    - name: Commit and Push Changes
      if: steps.version.outputs.release_needed == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "chore: release v${{ steps.version.outputs.version }}"
        git push origin HEAD:main

    - name: Generate changelog
      id: changelog
      if: steps.version.outputs.release_needed == 'true'
      shell: bash
      run: |
        # Fetch the latest changes from the remote
        git fetch origin main

        # Check if there are any tags
        if git describe --tags --abbrev=0 --always >/dev/null 2>&1; then
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 --always)
          # Generate changelog with commit messages since the latest tag up to origin/main
          changelog=$(git log $latest_tag..origin/main --pretty=format:"%s" --no-merges)
        else
          # No tags found, generate changelog from the beginning of the repo up to origin/main
          changelog=$(git log origin/main --pretty=format:"%s" --no-merges)
        fi

        # Output the changelog
        printf "changelog<<EOF\n%s\nEOF\n" "$changelog" >> $GITHUB_ENV

    - name: Create Release
      if: steps.version.outputs.release_needed == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        gh release create v${{ steps.version.outputs.version }} \
          --title "Release ${{ steps.version.outputs.version }}" \
          --notes "${{ steps.changelog.outputs.changelog }}"
