name: 'Create Convco Release'
description: 'Create a new release based on Conventional Commits'

inputs:
  github-token:
    description: 'GitHub token for creating the release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history

    - name: Fetch all tags
      run: |
        git fetch --prune --tags origin
        git fetch --all
      shell: bash

    - name: ASDF Setup
      uses: ./.github/actions/asdf-setup
      with:
        plugins: '["bun@latest"]'

    - name: Sync package.json version with latest tag
      id: sync-version
      shell: bash
      run: |
        # List tags for debugging
        echo "Available tags:"
        git tag -l
        
        # Get latest tag using git tag sorting
        latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n1)
        if [ -z "$latest_tag" ]; then
          echo "Warning: Could not find any tags. Using initial version."
          latest_tag="v0.0.0"
        fi
        
        echo "Latest tag: $latest_tag"
        latest_tag_version=${latest_tag#v}
        
        # Get the current package.json version
        package_version=$(node -p "require('./package.json').version")
        echo "Package.json version: $package_version"

        # Compare and update package.json if necessary
        if [ "$(printf '%s\n' "$latest_tag_version" "$package_version" | sort -V | head -n1)" != "$latest_tag_version" ]; then
          echo "Updating package.json version from $package_version to $latest_tag_version"
          jq --arg version "$latest_tag_version" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(release): v$latest_tag_version"
          git push origin HEAD:main
        fi

    - name: Determine new version and update package.json
      id: version
      shell: bash
      run: |
        # Configure git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Get current branch name
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        echo "Current branch: $current_branch"
        
        # Get latest tag using git tag sorting
        latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n1)
        if [ -z "$latest_tag" ]; then
          echo "No tags found. Using v0.0.0 as base version."
          latest_tag="v0.0.0"
        fi
        echo "Latest tag: $latest_tag"
        
        # First, update package.json to match the latest tag
        latest_version=${latest_tag#v}
        jq --arg version "$latest_version" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
        
        # Now run standard-version to determine the next version
        if ! bunx standard-version --release-as auto --skip.tag; then
          echo "Error: Failed to determine new version"
          exit 1
        fi

        # Get and validate the new version
        new_version=$(node -p "require('./package.json').version")
        echo "New version after standard-version: $new_version"
        
        if [ -z "$new_version" ] || [ "$new_version" = "null" ] || [ "$new_version" = "$latest_version" ]; then
          echo "Error: Invalid or unchanged version detected"
          exit 1
        fi
        
        echo "version=$new_version" >> $GITHUB_OUTPUT
        echo "release_needed=true" >> $GITHUB_OUTPUT

    - name: Commit and Push Changes
      if: steps.version.outputs.release_needed == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "chore: release v${{ steps.version.outputs.version }}"
        git push origin HEAD:main

    - name: Generate changelog
      id: changelog
      if: steps.version.outputs.release_needed == 'true'
      shell: bash
      run: |
        # Fetch the latest changes from the remote
        git fetch origin main

        # Check if there are any tags
        if git describe --tags --abbrev=0 --always >/dev/null 2>&1; then
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 --always)
          # Generate changelog with commit messages since the latest tag up to origin/main
          changelog=$(git log $latest_tag..origin/main --pretty=format:"%s" --no-merges)
        else
          # No tags found, generate changelog from the beginning of the repo up to origin/main
          changelog=$(git log origin/main --pretty=format:"%s" --no-merges)
        fi

        # Output the changelog
        printf "changelog<<EOF\n%s\nEOF\n" "$changelog" >> $GITHUB_ENV

    - name: Create Release
      if: steps.version.outputs.release_needed == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        gh release create v${{ steps.version.outputs.version }} \
          --title "Release ${{ steps.version.outputs.version }}" \
          --notes "${{ steps.changelog.outputs.changelog }}"
