name: 'Create Release'
description: 'Creates a new release based on conventional commits'

inputs:
  github-token:
    description: 'GitHub token for creating the release'
    required: true

outputs:
  released:
    description: 'Whether a release was created'
    value: ${{ steps.version.outputs.released }}
  version:
    description: 'The version that was released'
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Setup Action
      shell: bash
      run: |
        TEMP_DIR=$(mktemp -d)
        cp ${{ github.action_path }}/*.ts "$TEMP_DIR/"
        echo "ACTION_TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV

    - name: Determine Next Version
      id: version
      shell: bash
      run: bun run "$ACTION_TEMP_DIR/getNextVersion.ts"

    - name: Create GitHub Release
      if: steps.version.outputs.released == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        version="${{ steps.version.outputs.version }}"
        gh release create "$version" \
          --title "$version" \
          --generate-notes
