name: 'Create Release'
description: 'Creates a new release based on conventional commits'

inputs:
  github-token:
    description: 'GitHub token for creating the release'
    required: true
  dry-run:
    description: 'Run in dry-run mode without making actual changes'
    required: false
    default: 'false'

outputs:
  version:
    description: 'The version that was or would be released'
    value: ${{ steps.semver.outputs.version }}
  release_needed:
    description: 'Whether a release is needed'
    value: ${{ steps.semver.outputs.released }}

runs:
  using: "composite"
  steps:
    - name: Checkout with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine Next Version
      id: semver
      uses: grumpy-programmer/conventional-commits-semver-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DRY_RUN: ${{ inputs.dry-run }}

    - name: Create Release
      if: ${{ inputs.dry-run != 'true' && steps.semver.outputs.released == 'true' }}
      uses: ncipollo/release-action@v1.12.0
      with:
        tag_name: ${{ steps.semver.outputs.version }}
        release_name: Release ${{ steps.semver.outputs.version }}
        body: "See the changelog for details."
        draft: false
        prerelease: false
        token: ${{ inputs.github-token }}
