export { classNames } from './functions/classNames'
export { clone } from './functions/clone'
export { Color } from './functions/Color'
export { dataAttributes } from './functions/dataAttributes'
export { deburr } from './functions/deburr'
export { decode, encode } from './functions/encode'
export { deepEquals } from './functions/deepEquals'
export { formatBytes } from './functions/formatBytes'
export { formatMilliseconds } from './functions/formatMilliseconds'
export { formatNumber } from './functions/formatNumber'
export { get } from './functions/get'
export { getLocale } from './functions/getLocale'
export { hash } from './functions/hash'
export { HttpVerb } from './types/HttpVerb'
export { isRefObject } from './functions/isRefObject'
export { isNil } from './functions/isNil'
export { kebabCase } from './functions/kebabCase'
export { match } from './functions/match'
export { matchTemplateURI } from './functions/matchTemplateURI'
export { Milliseconds } from './constants/Milliseconds'
export { noop } from './functions/noop'
export { parseMilliseconds } from './functions/parseMilliseconds'
export { parseTemplateURI } from './functions/parseTemplateURI'
export { parseURI } from './functions/parseURI'
export { set } from './functions/set'
export type { URI } from './types/URI'
