export { classNames } from './functions/classNames'
export { dataAttributes } from './functions/dataAttributes'
export { deburr } from './functions/deburr'
export { isNil } from './functions/isNil'
export { kebabCase } from './functions/kebabCase'
export { matchURI } from './functions/matchURI'
export { parseURI } from './functions/parseURI'
export { HttpVerb } from './types/HttpVerb'