name: 'Check Conventional Commits and PR Title'
description: 'Check if the commits and PR title are following the Conventional Commits specification'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check PR Title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        validateSingleCommit: true
