name: 'Check Conventional Commits and PR Title'
description: 'Check if the commits and PR title are following the Conventional Commits specification'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check PR Title
      id: check_pr_title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        validateSingleCommit: true

    - name: Set output for valid flag
      id: set_output
      shell: bash
      run: |
        if [[ "${{ steps.check_pr_title.outputs.valid }}" == "true" ]]; then
          echo "valid=true" >> $GITHUB_ENV
        else
          echo "valid=false" >> $GITHUB_ENV
        fi
