name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enforce-convco
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - name: Run ESLint
        run: bun eslint

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - run: bun test

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/asdf-setup
      - name: Run TypeScript Type Check
        run: bun tsc

  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/asdf-setup

      - name: Identify Changed Workspaces
        id: changes
        run: |
          changed=$(bun workspace changed)
          echo "Changed workspaces: $changed"
          echo "workspaces=$changed" >> $GITHUB_OUTPUT

      - name: Dry Run Publish Changed Workspaces
        if: steps.changes.outputs.workspaces != '[]'
        run: |
          workspaces='${{ steps.changes.outputs.workspaces }}'
          version='${{ github.run_number }}-alpha'

          for workspace in $(echo "$workspaces" | jq -r '.[]'); do
            echo "Dry run publishing $workspace@$version"
            bun ws publish --only "$workspace" --version "$version" --dryRun || {
              echo "::error::Failed to dry run publish $workspace"
              exit 1
            }
          done

  required:
    if: always()
    needs:
      - check-pr-title
      - eslint
      - run-tests
      - type-check
      - publish-dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Check if required jobs passed or were skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more required jobs failed"
            exit 1
          else
            echo "All required jobs have passed or were skipped!"
          fi
