name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enforce-convco
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - name: Run ESLint
        run: bun eslint

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - run: bun test

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - name: Run TypeScript Type Check
        run: bun tsc

  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Tags
        run: |
          git fetch --prune --unshallow --tags origin
          echo "Available tags: $(git tag -l)"
      - uses: ./.github/actions/asdf-setup

      - name: Identify Changed Packages
        id: changes
        run: |
          echo "Latest tag: $(git describe --tags --abbrev=0)"
          changed=$(bun workspace changed --only '^@basis/')
          echo "Changed packages: $changed"
          echo "packages=$changed" >> $GITHUB_OUTPUT
      - name: Build Changed Packages
        run: |
          packages='${{ steps.changes.outputs.packages }}'
          echo "Packages to build: $packages"
          if [[ -n "$packages" && "$packages" != "[]" ]]; then
            for package in $(echo "$packages" | jq -r '.[]'); do
              echo "Building $package"
              bun workspace build "$package" -v "0.0.0-test"
            done
          else
            echo "No packages changed"
          fi

  required:
    if: always()
    needs:
      - check-pr-title
      - eslint
      - run-tests
      - type-check
      - build-packages
    runs-on: ubuntu-latest
    steps:
      - name: Check if required jobs passed or were skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more required jobs failed"
            exit 1
          else
            echo "All required jobs have passed or were skipped!"
          fi
