name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enforce-convco
        id: enforce-convco
      - name: PR Title Comment
        uses: actions/github-script@v5
        with:
          script: |
            const title = context.payload.pull_request.title;
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Define the comment body based on title validity
            const isValid = /^([a-z]+)(\([a-zA-Z0-9-]+\))?: .+/.test(title);
            const commentBody = isValid 
              ? '✅ The PR title is valid.' 
              : '❌ The PR title does not follow the Conventional Commits format. Please update it.';

            // Find an existing comment by this action
            const existingComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes('PR title'));

            if (existingComment) {
              await github.rest.issues.updateComment({
                comment_id: existingComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            }

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - run: bun test

  required:
    if: always()
    needs: [check-pr-title, run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check if required jobs passed or were skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more required jobs failed"
            exit 1
          else
            echo "All required jobs have passed or were skipped!"
          fi

