name: PR Validation

on:
  pull_request:
    types: [opened, edited]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enforce-convco
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
