name: Release

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/asdf-setup

      - name: Create Release
        id: create_release
        uses: ./.github/actions/create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if Version Created
        id: release_created
        run: |
          if [[ -n "${{ steps.create_release.outputs.released }}" ]]; then
            echo "should_publish=true" >> $GITHUB_OUTPUT
            echo "version=${{ steps.create_release.outputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "No new version created. Skipping publication."
            echo "should_publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Identify Changed Workspaces
        id: changes
        run: |
          changed=$(bun workspace changed --only '^@basis/')
          echo "Changed workspaces: $changed"
          echo "workspaces=$changed" >> $GITHUB_OUTPUT

      - name: Publish Changed Workspaces to JSR
        if: steps.changes.outputs.workspaces != '[]' && steps.release_created.outputs.should_publish == 'true'
        run: |
          workspaces='${{ steps.changes.outputs.workspaces }}'
          version='${{ steps.release_created.outputs.version }}'
          
          for workspace in $(echo "$workspaces" | jq -r '.[]'); do
            echo "Publishing $workspace@$version to JSR"
            bun ws publish --only "$workspace" --version "$version" || {
              echo "::error::Failed to publish $workspace to JSR"
              exit 1
            }
          done
