name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ASDF Setup
        uses: ./.github/actions/asdf-setup
        with:
          plugins: '["bun@latest"]'

      - name: Check Conventional Commits
        uses: ./.github/actions/enforce-convco

      - name: Determine new version
        id: version
        run: |
          # Use bunx to run convco to determine the next version
          version=$(bunx convco version --dry-run | grep "tagging release" | awk '{print $3}')
          echo "version=$version" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        run: |
          # Generate changelog using convco
          changelog=$(bunx convco changelog --from $(git describe --tags --abbrev=0) --to HEAD)
          echo "changelog=$changelog" >> $GITHUB_ENV

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.version.outputs.version }} \
            --title "Release ${{ steps.version.outputs.version }}" \
            --notes "${{ steps.changelog.outputs.changelog }}"
        shell: bash
